<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><CopperOSUseLocalCopperSharp>true</CopperOSUseLocalCopperSharp></PropertyGroup>
  <Import Project="../../../CopperOS.Portable.props" />
  <PropertyGroup>
    <AssemblyName>CopperOS.Commands.BootSessionLauncher</AssemblyName>
    <RootNamespace>CopperOS.Commands.BootSessionLauncher</RootNamespace>
    <ImplicitUsings>false</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CopperSharp.Sdk.Amiga.Support" Version="$(CopperSharpSdkAmigaVersion)" />
  </ItemGroup>
</Project>
