#!/usr/bin/env python3
"""Generate canonical object-like MUI constants from the ABI ledger."""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path


HAND_WRITTEN = {"MUI_MAXMAX", "MUIMASTER_VMIN", "MUIMASTER_VLATEST"}


def constants(inventory: dict) -> list[tuple[str, int | str, dict]]:
    result: dict[str, tuple[int | str, dict]] = {}
    for row in inventory["macros"]:
        if row["parameters"] or row["name"] in HAND_WRITTEN:
            continue
        value = row.get("value", row.get("profile_value"))
        if value is None:
            value = row.get("profile_value")
        if value is None:
            continue
        result.setdefault(row["name"], (value, row))
    return [(name, value, row) for name, (value, row) in sorted(result.items())]


def literal(value: int | str) -> tuple[str, str]:
    if isinstance(value, str):
        return "string", json.dumps(value, ensure_ascii=True)
    if value < 0:
        return "int", str(value)
    return "uint", f"0x{value & 0xFFFF_FFFF:08x}u"


def symbol_path(name: str) -> str:
    for prefix in ("MUIA_", "MUIM_", "MUIV_", "MUIC_", "MUIF_", "MUIO_", "MUII_", "MUIX_", "MUIE_"):
        if name.startswith(prefix):
            return name[len(prefix):].replace("_", ".")
    return name


def summary(name: str) -> str:
    path = html.escape(symbol_path(name))
    descriptions = {
        "MUIA_": "MUI attribute identifier",
        "MUIM_": "MUI method identifier",
        "MUIV_": "MUI special value",
        "MUIC_": "MUI class identifier",
        "MUIF_": "MUI flag value",
        "MUIO_": "MUI object-construction value",
        "MUII_": "MUI image specification value",
        "MUIX_": "MUI text formatting code",
        "MUIE_": "MUI error value",
    }
    kind = next((description for prefix, description in descriptions.items() if name.startswith(prefix)), "MUI ABI constant")
    return f"{kind} for <c>{path}</c>."


def documentation(row: dict) -> list[str]:
    lines = [f"\t/// <summary>{summary(row['name'])}</summary>"]
    details: list[str] = []
    access = row.get("access", [])
    if access:
        labels = {"initialize": "initialization", "set": "setting", "get": "reading"}
        operations = [labels[item] for item in access]
        if len(operations) == 1:
            operation_text = operations[0]
        elif len(operations) == 2:
            operation_text = " and ".join(operations)
        else:
            operation_text = ", ".join(operations[:-1]) + ", and " + operations[-1]
        details.append(f"The SDK marks this attribute for {operation_text}.")
    value_kinds = {
        "boolean": "a Boolean value",
        "signed-integer": "a signed integer",
        "unsigned-integer": "an unsigned integer",
        "string-pointer": "a guest string pointer",
        "hook-pointer": "a guest hook pointer",
        "tag-list-pointer": "a guest tag-list pointer",
        "mui-object-pointer": "a guest MUI object pointer",
        "pointer": "a guest pointer",
    }
    if row.get("value_kind") in value_kinds:
        details.append(f"Its associated value is {value_kinds[row['value_kind']]}.")
    if row.get("introduced_version") is not None:
        details.append(f"The SDK marks it as available since MUI version {row['introduced_version']}.")
    if row.get("obsolete_surface"):
        details.append("This identifier belongs to an obsolete compatibility surface.")
    if row.get("profile_choice") == "USE_HYPERLINK_MCC":
        details.append("The MorphOs320M68k profile resolves this conditional identifier through Hyperlink.mcc compatibility.")
    if details:
        lines.append(f"\t/// <remarks>{html.escape(' '.join(details))}</remarks>")
    return lines


def generate_source(items: list[tuple[str, int | str, dict]]) -> str:
    lines = [
        "/*", "- Copyright (C) 2026 Ilkka Lehtoranta",
        "- SPDX-License-Identifier: MIT", "*/", "",
        "// Generated by CopperOS/tools/MuiInventory/generate_csharp_constants.py.",
        "// Public identifiers and fixed-width ABI facts only.", "",
        "namespace Amiga.MUI;", "", "public static partial class MUIConstants", "{",
    ]
    for name, value, row in items:
        cs_type, cs_value = literal(value)
        lines.extend(documentation(row))
        lines.append(f"\tpublic const {cs_type} {name} = {cs_value};")
    lines.extend(["}", ""])
    return "\n".join(lines)


def generate_tests(items: list[tuple[str, int | str, dict]]) -> str:
    lines = [
        "/*", "- Copyright (C) 2026 Ilkka Lehtoranta",
        "- SPDX-License-Identifier: MIT", "*/", "",
        "// Generated by CopperOS/tools/MuiInventory/generate_csharp_constants.py.",
        "// Public identifiers and fixed-width ABI facts only.", "",
        "using Amiga.MUI;", "using Xunit;", "", "namespace CopperSharp.Compiler.Tests;", "",
        "public sealed class MuiConstantAbiTests", "{",
    ]
    chunk_size = 100
    for index in range(0, len(items), chunk_size):
        chunk = items[index:index + chunk_size]
        lines.extend(["\t[Fact]", f"\tpublic void CanonicalConstants_{index // chunk_size:00}_AreExact()", "\t{"])
        for name, value, _ in chunk:
            _, expected = literal(value)
            lines.append(f"\t\tAssert.Equal({expected}, MUIConstants.{name});")
        lines.extend(["\t}", ""])
    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--inventory", type=Path, required=True)
    parser.add_argument("--constants-output", type=Path, required=True)
    parser.add_argument("--tests-output", type=Path, required=True)
    args = parser.parse_args()

    inventory = json.loads(args.inventory.read_text(encoding="utf-8"))
    items = constants(inventory)
    if len(items) < 1800:
        raise ValueError(f"Expected at least 1800 canonical constants, found {len(items)}")
    args.constants_output.write_text(generate_source(items), encoding="utf-8", newline="\n")
    args.tests_output.write_text(generate_tests(items), encoding="utf-8", newline="\n")
    print(json.dumps({"constants": len(items), "source": str(args.constants_output), "tests": str(args.tests_output)}, indent=2))


if __name__ == "__main__":
    main()
