#!/usr/bin/env python3
"""Generate exhaustive MUImaster LVO/register annotation tests from the ABI ledger."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def generate(vectors: list[dict]) -> str:
    lines = [
        "/*", "- Copyright (C) 2026 Ilkka Lehtoranta", "- SPDX-License-Identifier: MIT", "*/", "",
        "// Generated by CopperOS/tools/MuiInventory/generate_csharp_vector_tests.py.",
        "// Public identifiers and fixed-width ABI facts only.", "",
        "using System.Reflection;", "using Amiga;", "using CopperSharp.Compiler;",
        "using CopperSharp.Sdk.Amiga;", "using Xunit;", "", "namespace CopperSharp.Compiler.Tests;", "",
        "public sealed class MuiVectorAbiTests", "{", "\t[Fact]",
        "\tpublic void EveryPublicVectorHasExactLvoAndRegisters()", "\t{",
    ]
    for vector in vectors:
        registers = ", ".join(f"M68kRegister.{item}" for item in vector["registers"])
        suffix = f", {registers}" if registers else ""
        lines.append(f"\t\tVector(nameof(MUIMaster.{vector['name']}), {vector['lvo']}{suffix});")
    lines.extend([
        "\t}", "", "\tprivate static void Vector(string name, int lvo, params M68kRegister[] registers)", "\t{",
        "\t\tvar method = typeof(MUIMaster).GetMethod(name, BindingFlags.Public | BindingFlags.Static);",
        "\t\tAssert.NotNull(method);",
        "\t\tAssert.Equal(lvo, method!.GetCustomAttribute<AmigaLvoAttribute>()?.Offset);",
        "\t\tvar parameters = method.GetParameters();",
        "\t\tAssert.Equal(registers.Length, parameters.Length);",
        "\t\tfor (var index = 0; index < parameters.Length; index++)",
        "\t\t\tAssert.Equal(registers[index], parameters[index].GetCustomAttribute<M68kRegisterAttribute>()?.Register);",
        "\t\tif (method.ReturnType != typeof(void))",
        "\t\t\tAssert.Equal(M68kRegister.D0, method.ReturnParameter.GetCustomAttribute<M68kRegisterAttribute>()?.Register);",
        "\t}", "}", "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--inventory", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    data = json.loads(args.inventory.read_text(encoding="utf-8"))
    vectors = data["vectors"]
    if len(vectors) != 27 or any(item["comparison"] != "match" for item in vectors):
        raise ValueError("Expected 27 exact public vectors")
    args.output.write_text(generate(vectors), encoding="utf-8", newline="\n")
    print(json.dumps({"vectors": len(vectors), "output": str(args.output)}, indent=2))


if __name__ == "__main__":
    main()
