param([string]$DotnetPath = 'dotnet', [string]$CopperSharpRoot = (Join-Path $PSScriptRoot '..\..\..\CopperSharp68k'), [string]$OutputDirectory)
$ErrorActionPreference = 'Stop'; Set-StrictMode -Version Latest
$repo=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$project=Join-Path $repo 'tests\Commands.AddBuffersNativeRoot\CopperOS.Commands.AddBuffersNativeRoot.csproj'
$root=Join-Path $repo 'tests\Commands.AddBuffersNativeRoot\bin\Release\net10.0'
$cli=Join-Path $CopperSharpRoot 'Compiler.Cli\bin\Release\net10.0\CopperSharp.Compiler.Cli.dll'
$run=if($OutputDirectory){[IO.Path]::GetFullPath($OutputDirectory)}else{Join-Path $root ('qualification-copy-destination-static\'+[guid]::NewGuid().ToString('N'))};New-Item -ItemType Directory -Force $run|Out-Null
& $DotnetPath build (Join-Path $CopperSharpRoot 'Compiler.Cli\CopperSharp.Compiler.Cli.csproj') -c Release --nologo;if($LASTEXITCODE){throw 'Compiler build failed.'}
& $DotnetPath build $project -c Release --nologo;if($LASTEXITCODE){throw 'Root build failed.'}
$support=Get-ChildItem (Join-Path $env:USERPROFILE '.nuget\packages\coppersharp.sdk.amiga.support') -Recurse -Filter CopperSharp.Sdk.Amiga.Support.dll|Sort-Object FullName -Descending|Select-Object -First 1 -ExpandProperty FullName;if(!$support){throw 'Support assembly missing.'};$artifacts=@()
foreach($cpu in '68000','68020','68040'){$hunk=Join-Path $run "copy-destination-$cpu.hunk";$report="$hunk.compatibility.json";& $DotnetPath $cli (Join-Path $root 'CopperOS.Commands.AddBuffersNativeRoot.dll') '--entry' 'CopperOS.Commands.AddBuffersNativeRoot.NativeMorphOSCopyDestinationEntry::Main' '--platform' amiga '--cpu' $cpu '--clr' always '--exceptions' yolo '--format' hunk '--runtime' resident '--memory' none '--peephole' disabled '--managed-assembly' (Join-Path $root 'CopperSharp.Sdk.Amiga.dll') '--managed-assembly' $support '--managed-assembly' (Join-Path $root 'CopperSharp.Compiler.dll') '--output' $hunk '--compatibility-report' $report;if($LASTEXITCODE){throw "Compile failed for $cpu."};$receipt=Get-Content $report -Raw|ConvertFrom-Json;$native=$receipt.NativeCompatibility;if(!$receipt.IsCompatible -or $receipt.ReachableMethodCount -ne 5 -or $native.RuntimeFeatureCount -ne 0 -or $native.RuntimeHelperCount -ne 0 -or $native.ExternalNativeTargetCount -ne 0 -or $native.ExceptionRegionCount -ne 0 -or $native.FatalMachineFaultSiteCount -ne 0){throw "Receipt incomplete for $cpu."};$file=Get-Item $hunk;$artifacts += [ordered]@{cpu=$cpu;bytes=$file.Length;sha256=(Get-FileHash $hunk -Algorithm SHA256).Hash.ToLowerInvariant();reachableMethods=$receipt.ReachableMethodCount}}
[ordered]@{schemaVersion=1;suite='CC13-Copy-destination-static';status='passed';runtime='resident';entry='CopperOS.Commands.AddBuffersNativeRoot.NativeMorphOSCopyDestinationEntry::Main';scope='Static three-CPU pure/resident compilation for Copy non-force TestDest. No native execution vectors, parser, FORCEOVERWRITE, destination creation, matcher, metadata, packaged command, or original parity claim.';artifacts=$artifacts}|ConvertTo-Json -Depth 6|Set-Content (Join-Path $run 'qualification.json') -Encoding utf8
