<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\CopperOS.Portable.props" />
  <PropertyGroup>
    <AssemblyName>CopperOS.Commands</AssemblyName>
    <RootNamespace>CopperOS.Commands</RootNamespace>
    <ImplicitUsings>false</ImplicitUsings>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\System\Shell\CopperOS.Shell.csproj" />
  </ItemGroup>
</Project>
