<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>CopperOS.Commands.Exe2ArcIoNativeExecution</AssemblyName>
    <RootNamespace>CopperOS.Commands.Exe2ArcIoNativeExecution</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Copper68k" Version="1.4.0" />
    <Compile Include="..\Commands.NativeExecution\HunkImage.cs" Link="HunkImage.cs" />
  </ItemGroup>
</Project>
