<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\CopperOS.Portable.props" />
  <PropertyGroup>
    <AssemblyName>CopperOS.Shell</AssemblyName>
    <RootNamespace>CopperOS.Shell</RootNamespace>
    <ImplicitUsings>false</ImplicitUsings>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="DosShellPlatform.cs;DosShellNativeEntrypoints.cs;DosShellNativeParkEntrypoint.cs;DosShellNativePlatform.cs;DosShellNativeLaunchCore.cs" />
  </ItemGroup>
</Project>
