<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <CopperOSUseLocalCopperSharp>true</CopperOSUseLocalCopperSharp>
  </PropertyGroup>
  <Import Project="..\..\CopperOS.Portable.props" />
  <PropertyGroup>
    <AssemblyName>CopperOS.Commands.TypeNativeRoot</AssemblyName>
    <RootNamespace>CopperOS.Commands.TypeNativeRoot</RootNamespace>
    <ImplicitUsings>false</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CopperSharp.Sdk.Amiga.Support" Version="$(CopperSharpSdkAmigaVersion)" />
    <Compile Include="..\..\src\Commands\TypeTextFormatter.cs" Link="TypeTextFormatter.cs" />
    <Compile Include="..\..\src\Commands\Native\NativeCommandArguments.cs" Link="NativeCommandArguments.cs" />
    <Compile Include="..\..\src\Commands\Native\NativeCommandStartup.cs" Link="NativeCommandStartup.cs" />
    <Compile Include="..\..\src\Commands\Native\NativeMorphOSTypeCommand.cs" Link="NativeMorphOSTypeCommand.cs" />
    <Compile Include="..\..\src\Commands\Native\NativeWorkbench31TypeCommand.cs" Link="NativeWorkbench31TypeCommand.cs" />
    <Compile Include="..\..\src\Commands\Native\NativeMorphOSTypeHexIo.cs" Link="NativeMorphOSTypeHexIo.cs" />
    <Compile Include="..\..\src\Commands\Native\NativeMorphOSTypeTextIo.cs" Link="NativeMorphOSTypeTextIo.cs" />
  </ItemGroup>
</Project>
