<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <CopperOSUseLocalCopperSharp>true</CopperOSUseLocalCopperSharp>
  </PropertyGroup>
  <Import Project="..\..\CopperOS.Portable.props" />
  <PropertyGroup>
    <CopperOSReferenceSdkAmigaSupport>true</CopperOSReferenceSdkAmigaSupport>
    <AssemblyName>CopperOS.Commands.TypeNativeRoot</AssemblyName>
    <RootNamespace>CopperOS.Commands.TypeNativeRoot</RootNamespace>
    <ImplicitUsings>false</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\src\Commands\Type\TypeTextFormatter.cs" Link="TypeTextFormatter.cs" />
  </ItemGroup>
</Project>

