using System.Text;
using Amiga;
using static CopperOS.Commands.NativeExecution.CommandTestBus;
namespace CopperOS.Commands.NativeExecution;
internal sealed record CopyNonFileSystemProbeCase(bool FileSystem,bool CopyMove,uint Capacity,bool Lock,bool Success,int Error,string Copy);
internal sealed class CopyNonFileSystemNativeLayout(uint c){public uint Control{get;}=c;public int Tests,Locks,Unlocks;public bool Contains(uint a,int s)=>a>=Control&&(ulong)a+(uint)s<=(ulong)Control+96;}
internal sealed partial class ProbeFixture
{
 public const string CopyNonFileSystemProbeSuite="copy-nonfilesystem-native-entry-vector-fixture";
 private List<object> RunCopyNonFileSystemProbeCases(){ProbeCase[] c=[Case("fallback",false,true,32,true,true,0,"NET:pipe"),Case("filesystem",true,true,32,false,false,0,""),Case("not-copy",false,false,32,false,false,0,""),Case("capacity",false,true,4,false,false,(int)DOS.Error.LineTooLong,""),Case("lock-failure",false,true,32,false,false,401,"NET:pipe"),Case("no-colon",false,true,32,false,false,0,"")];var r=new List<object>();foreach(var x in c)r.AddRange(Execute([x],false));r.AddRange(Execute([c[0] with{Name="interleaved-fallback"},c[4] with{Name="interleaved-lock-failure"}],true));Bus.AssertImageUnchanged();return r;}
 private static ProbeCase Case(string n,bool fs,bool cm,uint cap,bool l,bool s,int e,string copy)=>new(n,"",s?DOS.RETURN_OK:DOS.RETURN_FAIL,e,""){EntryLength=28,CopyNonFileSystem=new(fs,cm,cap,l,s,e,copy)};
 private void PrepareCopyNonFileSystemProbe(Invocation i){var c=i.Arguments;Bus.Memory.AsSpan((int)c,96).Clear();i.CopyNonFileSystemLayout=new(c);var p=i.Definition.CopyNonFileSystem!;var n=i.Definition.Name=="no-colon"?"pipe":"NET:pipe";Encoding.Latin1.GetBytes(n).CopyTo(Bus.Memory.AsSpan((int)(c+40)));Bus.Memory[c+40+(uint)n.Length]=0;Bus.Long(c,c+40);Bus.Long(c+4,c+64);Bus.Long(c+8,p.Capacity);Bus.Long(c+12,p.CopyMove?1u:0);}
 private void VerifyCopyNonFileSystemProbe(Invocation i){var p=i.Definition.CopyNonFileSystem!;var l=i.CopyNonFileSystemLayout!;Require((Bus.Long(l.Control+16)!=0)==p.Success&&Bus.Long(l.Control+20)==(p.Success?1u:0)&&unchecked((int)Bus.Long(l.Control+24))==p.Error&&Bus.CString(l.Control+64)==p.Copy,$"Copy non-filesystem result differs: lock={Bus.Long(l.Control+16)}, flag={Bus.Long(l.Control+20)}, error={unchecked((int)Bus.Long(l.Control+24))}, copy={Bus.CString(l.Control+64)}.");var callsLock=i.Definition.Name!="no-colon"&&!p.FileSystem&&p.CopyMove&&p.Capacity>=9;Require(l.Tests==((i.Definition.Name=="no-colon")?0:1)&&l.Locks==(callsLock?1:0)&&l.Unlocks==(p.Lock?1:0),$"Copy non-filesystem ownership differs: tests={l.Tests}, locks={l.Locks}, unlocks={l.Unlocks}.");i.CopyNonFileSystemLayout=null;}
 private void RegisterCopyNonFileSystemProbeDos(uint b){Register(b,-708,"IsFileSystem",(s,i)=>{var p=i.Definition.CopyNonFileSystem!;var l=i.CopyNonFileSystemLayout!;Require(Bus.CString(s.D[1])=="NET:","Copy IsFileSystem ABI differs.");l.Tests++;return p.FileSystem?1u:0;});Register(b,DosLvo.Lock,"Lock",(s,i)=>{var p=i.Definition.CopyNonFileSystem!;var l=i.CopyNonFileSystemLayout!;Require(s.D[1]!=0&&Bus.CString(s.D[1])==""&&s.D[2]==unchecked((uint)DOS.LockMode.Shared),"Copy empty Lock ABI differs.");l.Locks++;if(!p.Lock)i.IoError=p.Error;return p.Lock?0x150u:0;});Register(b,DosLvo.UnLock,"UnLock",(_,i)=>{i.CopyNonFileSystemLayout!.Unlocks++;return 0;});Register(b,DosLvo.IoErr,"IoErr",(_,i)=>unchecked((uint)i.IoError));Register(b,DosLvo.SetIoErr,"SetIoErr",(s,i)=>{i.IoError=unchecked((int)s.D[1]);return 0;});}
}
