using System.Text;
using Amiga;
using static CopperOS.Commands.NativeExecution.CommandTestBus;
namespace CopperOS.Commands.NativeExecution;
internal sealed record CopyOpenDestinationProbeCase(string Kind,int Result,int Error,bool NoFileSystem,int Locks,int Creates,int Unlocks);
internal sealed class CopyOpenDestinationNativeLayout(uint control){public uint Control{get;}=control;public int Locks,Creates,Unlocks,Tests;public bool Contains(uint a,int s)=>a>=Control&&(ulong)a+(uint)s<=(ulong)Control+512;}
internal sealed partial class ProbeFixture
{
 public const string CopyOpenDestinationProbeSuite="copy-open-destination-native-entry-vector-fixture";
 private List<object> RunCopyOpenDestinationProbeCases(){var c=new[]{C("nonfs",0,0,true,1,0,1),C("filesystem",0,0,false,2,1,2),C("create-failure",20,301,false,1,1,0)};var r=new List<object>();foreach(var x in c)r.AddRange(Execute([x],false));r.AddRange(Execute([c[0] with{Name="interleaved-nonfs"},c[1] with{Name="interleaved-filesystem"}],true));Bus.AssertImageUnchanged();return r;}
 private static ProbeCase C(string n,int r,int e,bool f,int l,int c,int u)=>new(n,"",r,e,""){EntryLength=32,CopyOpenDestination=new(n,r,e,f,l,c,u)};
 private void PrepareCopyOpenDestinationProbe(Invocation i){var c=i.Arguments;Bus.Memory.AsSpan((int)c,512).Clear();i.CopyOpenDestinationLayout=new(c);var p=i.Definition.CopyOpenDestination!;var n=p.Kind=="nonfs"?"NET:x":"RAM:a";Encoding.Latin1.GetBytes(n).CopyTo(Bus.Memory.AsSpan((int)(c+64)));Bus.Memory[c+64+(uint)n.Length]=0;Bus.Long(c,c+64);Bus.Long(c+4,c+192);Bus.Long(c+8,128);Bus.Long(c+12,1);}
 private void VerifyCopyOpenDestinationProbe(Invocation i){var p=i.Definition.CopyOpenDestination!;var l=i.CopyOpenDestinationLayout!;Require((Bus.Long(l.Control+20)!=0)==(p.Result==0)&& (Bus.Long(l.Control+24)!=0)==p.NoFileSystem&&unchecked((int)Bus.Long(l.Control+28))==p.Error&&l.Tests==1&&l.Locks==p.Locks&&l.Creates==p.Creates&&l.Unlocks==p.Unlocks,$"{i.Definition.Name}: OpenDest branch differs.");i.CopyOpenDestinationLayout=null;}
 private void RegisterCopyOpenDestinationProbeDos(uint b){Register(b,DosLvo.IsFileSystem,"IsFileSystem",(s,i)=>{var p=i.Definition.CopyOpenDestination!;var l=i.CopyOpenDestinationLayout!;Require(Bus.CString(s.D[1])==(p.Kind=="nonfs"?"NET:":"RAM:"),"OpenDest IsFileSystem ABI differs.");l.Tests++;return p.Kind=="nonfs"?0u:1;});Register(b,DosLvo.Lock,"Lock",(s,i)=>{var p=i.Definition.CopyOpenDestination!;var l=i.CopyOpenDestinationLayout!;var name=Bus.CString(s.D[1]);l.Locks++;Require(s.D[2]==unchecked((uint)DOS.LockMode.Shared),"OpenDest Lock mode differs.");if(p.Kind=="nonfs"){Require(s.D[1]!=0&&name=="","OpenDest requires an actual empty string.");return 0x150u;}if(l.Locks==2)return 0x180u;return 0;});Register(b,-120,"CreateDir",(_,i)=>{var p=i.Definition.CopyOpenDestination!;i.CopyOpenDestinationLayout!.Creates++;if(p.Kind=="create-failure"){i.IoError=p.Error;return 0;}return 0x170u;});Register(b,DosLvo.UnLock,"UnLock",(_,i)=>{i.CopyOpenDestinationLayout!.Unlocks++;return 0;});Register(b,DosLvo.IoErr,"IoErr",(_,i)=>unchecked((uint)i.IoError));Register(b,DosLvo.SetIoErr,"SetIoErr",(s,i)=>{i.IoError=unchecked((int)s.D[1]);return 0;});}
}
