using Amiga; using static CopperOS.Commands.NativeExecution.CommandTestBus;
namespace CopperOS.Commands.NativeExecution;
internal sealed record CopyLoopGuardProbeCase(string Kind,bool Loop,int Parents,int Unlocks);
internal sealed class CopyLoopGuardNativeLayout(uint c){public uint Control{get;}=c;public int Devices,Same,Parents,Unlocks;public bool Contains(uint a,int s)=>a>=Control&&(ulong)a+(uint)s<=(ulong)Control+32;}
internal sealed partial class ProbeFixture {
 public const string CopyLoopGuardProbeSuite="copy-loop-guard-native-entry-vector-fixture";
 private List<object> RunCopyLoopGuardProbeCases(){ProbeCase[] c=[C("different",false,0,0),C("ancestor",true,1,1),C("recursive",true,0,0),C("root",false,1,1),C("null-same",true,0,0),C("null-parent",false,1,0)];var r=new List<object>();foreach(var x in c)r.AddRange(Execute([x],false));r.AddRange(Execute([c[1] with{Name="interleaved-ancestor"},c[2] with{Name="interleaved-recursive"}],true));Bus.AssertImageUnchanged();return r;}
 private static ProbeCase C(string n,bool l,int p,int u)=>new(n,"",DOS.RETURN_OK,0,""){EntryLength=12,CopyLoopGuard=new(n,l,p,u)};
 private void PrepareCopyLoopGuardProbe(Invocation i){var c=i.Arguments;Bus.Memory.AsSpan((int)c,32).Clear();i.CopyLoopGuardLayout=new(c);Bus.Long(c,0x100);Bus.Long(c+4,i.Definition.CopyLoopGuard!.Kind.StartsWith("null-")?0u:0x200u);}
 private void VerifyCopyLoopGuardProbe(Invocation i){var p=i.Definition.CopyLoopGuard!;var l=i.CopyLoopGuardLayout!;Require((Bus.Long(l.Control+8)!=0)==p.Loop&&l.Devices==1&&l.Parents==p.Parents&&l.Unlocks==p.Unlocks,$"{i.Definition.Name}: devices={l.Devices}, loop={Bus.Long(l.Control+8)}, parents={l.Parents}, unlocks={l.Unlocks}.");i.CopyLoopGuardLayout=null;}
 private void RegisterCopyLoopGuardProbeDos(uint b){Register(b,DosLvo.SameDevice,"SameDevice",(_,i)=>{i.CopyLoopGuardLayout!.Devices++;return i.Definition.CopyLoopGuard!.Kind=="different"?0u:1;});Register(b,DosLvo.SameLock,"SameLock",(s,i)=>{var l=i.CopyLoopGuardLayout!;l.Same++;var k=i.Definition.CopyLoopGuard!.Kind;Require(s.D[1]==0x100&&s.D[2]==(k.StartsWith("null-")?0u:k=="ancestor"&&l.Same>1?0x100u:0x200u),"SameLock arguments differ.");return k=="null-same"||k=="recursive"||k=="ancestor"&&l.Same>1?0u:1;});Register(b,DosLvo.ParentDir,"ParentDir",(_,i)=>{i.CopyLoopGuardLayout!.Parents++;return i.Definition.CopyLoopGuard!.Kind=="ancestor"?0x100u:0;});Register(b,DosLvo.UnLock,"UnLock",(s,i)=>{Require(s.D[1]==(i.Definition.CopyLoopGuard!.Kind=="ancestor"?0x100u:0),"Ancestor cleanup differs.");i.CopyLoopGuardLayout!.Unlocks++;return 0;});Register(b,DosLvo.SetIoErr,"SetIoErr",(s,i)=>{i.IoError=unchecked((int)s.D[1]);return 0;});}
}
