<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <CopperOSUseLocalCopperSharp>true</CopperOSUseLocalCopperSharp>
  </PropertyGroup>
  <Import Project="..\..\CopperOS.Portable.props" />
  <PropertyGroup>
    <AssemblyName>CopperOS.Commands.MorphOSWaitNativeRoot</AssemblyName>
    <RootNamespace>CopperOS.Commands.MorphOSWaitNativeRoot</RootNamespace>
    <ImplicitUsings>false</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CopperSharp.Sdk.Amiga.Support" Version="$(CopperSharpSdkAmigaVersion)" />
    <Compile Include="..\..\src\Commands\Native\NativeCommandArguments.cs" Link="NativeCommandArguments.cs" />
    <Compile Include="..\..\src\Commands\Native\NativeCommandStartup.cs" Link="NativeCommandStartup.cs" />
    <Compile Include="..\..\src\Commands\Native\NativeMorphOSWaitCommand.cs" Link="NativeMorphOSWaitCommand.cs" />
  </ItemGroup>
</Project>
