<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CopperOS.Commands.WaitForPort</AssemblyName>
    <RootNamespace>CopperOS.Commands</RootNamespace>
    <RuntimeIdentifier>amiga-m68k</RuntimeIdentifier>
    <CopperOSCommandName>WaitForPort</CopperOSCommandName>
    <CopperOSCodeSizeOptimizations Condition="'$(CopperOSCodeSizeOptimizations)' == ''">on</CopperOSCodeSizeOptimizations>
    <CopperSharpEntry>CopperOS.Commands.Entries.WaitForPortEntry::Main</CopperSharpEntry>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common\CopperOS.Commands.Common.csproj" />
  </ItemGroup>
</Project>
