<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <CopperOSUseLocalCopperSharp>true</CopperOSUseLocalCopperSharp>
  </PropertyGroup>
  <Import Project="..\..\CopperOS.Portable.props" />
  <PropertyGroup>
    <CopperOSReferenceSdkAmigaSupport>true</CopperOSReferenceSdkAmigaSupport>
    <AssemblyName>CopperOS.Commands.EvalExpressionNativeRoot</AssemblyName>
    <RootNamespace>CopperOS.Commands.EvalExpressionNativeRoot</RootNamespace>
    <ImplicitUsings>false</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\src\Commands\Eval\EvalExpressionEvaluator.cs" Link="EvalExpressionEvaluator.cs" />
  </ItemGroup>
</Project>
